### ISSUE TITLE
(cocos2d-xna) ccTexture2D.setTexParameters() not Implemented

### ISSUE THREAD

**Issue by imwower** [mono/cocos2d-xna#59] opened 2013-04-23 12:36 UTC
```
    public void setTexParameters(ccTexParams texParams)
    {
        //throw new NotImplementedException();
    }
```

so, we can't use ccTexParams in xna just now, not as iOS?

![20130423203622](https://f.cloud.github.com/assets/1744486/414273/8ae2c5d4-ac12-11e2-84cc-5e2eed67caa7.jpg)

**Comment by kjpou1** [comment] 2013-04-23 12:57
George

Let us take a look at this.  Off the top of my head, if we can do this in XNA then we can implement this method.  Unfortunately that depends on MonoGame because we will have to map these to XNA semantics.  MonoGame is OpenGL, OGLES, DirectX.  Those types of parameters that are passed would not work, ie. 

```
ccTexParams params = {GL_LINEAR,GL_LINEAR,GL_CLAMP_TO_EDGE, GL_CLAMP_TO_EDGE};
sprite->getTexture()->setTexParameters(&params);
```

The parameters in above code are actually OpenGL parameters.  In XNA those would not be able to be passed as OpenGL but would need to use the XNA semantics.

**Comment by kjpou1** [comment] 2013-04-23 13:02
What we really need to do is set the SamplerState on the texture and if those are implemented in MonoGame then we should be ok.

Here is the current list that XNA supports:

Name    Description
    AnisotropicClamp    Contains default state for anisotropic filtering and texture coordinate clamping.
    AnisotropicWrap Contains default state for anisotropic filtering and texture coordinate wrapping.
    LinearClamp Contains default state for linear filtering and texture coordinate clamping.
    LinearWrap  Contains default state for linear filtering and texture coordinate wrapping.
    PointClamp  Contains default state for point filtering and texture coordinate clamping.
    PointWrap   Contains default state for point filtering and texture coordinate wrapping.

**Comment by imwower** [comment] 2013-04-23 13:22
thanks for your reply~
so, I have to search a better way to resolve it.

**Comment by kjpou1** [comment] 2013-04-23 13:35
George 

What are the exact parameters you need to pass?  If you can create a small sample for me to run against we can hopefully get this sorted out.

**Comment by imwower** [comment] 2013-04-23 14:23
well, my idea is just simple,
use a small image, instead of a big one, to make the scene looks like unlimited, width/height,
just like the CSS 'background-image' property,

**Comment by kjpou1** [comment] 2013-04-23 14:47
Like this:

http://msdn.microsoft.com/en-gb/library/bb975153.aspx

**Comment by imwower** [comment] 2013-04-23 15:28
yes, that is it~

**Comment by kjpou1** [comment] 2013-04-23 15:37
George

I am going to keep this issue open because it needs to be implemented.  We will take a look at it next.  

Thank you for reporting the issue.  I just wanted to make sure I understood exactly what you wanted.

**Comment by imwower** [comment] 2013-04-23 16:37
that exactly what I need.
thanks for your patience and hard work~
good luck~

**Comment by kjpou1** [comment] 2013-04-24 16:42
George

I think I have it all figured out.  Have to do some more translations between OpenGL and XNA Sampler States.

Will not be able to finish it today but hopefully tomorrow.

**Comment by imwower** [comment] 2013-04-24 19:19
wow, you make an effective job~ good luck~

**Comment by kjpou1** [comment] 2013-04-25 05:26
George

This should be done.  The SetTexParams is now a property called TexParams.

You can see how I used it here: https://github.com/mono/cocos2d-xna/blob/master/tests/tests/classes/tests/Texture2dTest/Texture2dTest.cs

Let me know if this works for you.

**Comment by imwower** [comment] 2013-04-25 08:42
thk U~
but I while debug with Texture2Dtest.cs, it throws an InvalidOperationException at line 466, 454 and so on,
detail:
can't change read only property: samplerState, samplerState first time binding to GraphicsDevice become read only,
if want change value, plz create a new instance

**Comment by kjpou1** [comment] 2013-04-25 09:23
George

What system/platform are you running on?

It seems to be the same as this one correct?  https://github.com/mono/cocos2d-xna/issues/71

But I am not having the same issue.  I wrote this on iOS and Mac with MonoGame so that might be the problem.

**Comment by kjpou1** [comment] 2013-04-25 10:03
George

I made a change and pushed it.  Could you try that one out for me.  

Make sure you update your repo.

**Comment by imwower** [comment] 2013-04-25 12:48
iam using windows(32bit),
this time, works well with the texture,
but after i change the test scenes a few times, she crashed again, and said: the collection data has changed

![20130425202608](https://f.cloud.github.com/assets/1744486/425151/61a6a8bc-ada6-11e2-8593-3e9a1f6b0d18.jpg)
![20130425203121](https://f.cloud.github.com/assets/1744486/425152/61d7a872-ada6-11e2-9426-1ac8ca119100.jpg)

**Comment by imwower** [comment] 2013-04-25 12:51
and the earlier error is same as issue #71

**Comment by kjpou1** [comment] 2013-04-25 13:11
George

That is Windows 32bit XNA or MonoGame? 

As far as the crash goes could you set up another issue for that.  I saw that myself a couple of times but have not had a chance to look at it yet.  I can fix it but not right this instance.

There is also a new Property I placed on the CCTexture2D for Non OpenGL systems that is named SamplerState.  For non opengl systems you would setup a new SamplerState and in this case it would be SamplerState.LinearWrap.  See if that works for you because the background is the same color but the pattern does not show up for you.

You can do something like this:             

sprite.Texture.SamplerState = SamplerState.LinearWrap;

That should give you a patterned look instead of a solid color.

**Comment by kjpou1** [comment] 2013-04-25 13:42
Pushed another change that should fix the crash which is caused by iterating over a Dictionary with a foreach.

Also added code to the Texture2DTests to add wrap and clamp for non OpenGL systems.

Can you give that a test for me.  That should be the last of the problems I am thinking assuming that the crash now does not happen.

**Comment by imwower** [comment] 2013-04-25 14:11
congratulations~you did an amazing work!
it works, finally.
PS: you forget to add CCScale9SpriteFile.cs and CCScale9SpriteFrame.cs to cocos2d.phone
(iam using windows XNA, 32bit. 64bit as well)
![20130425220242](https://f.cloud.github.com/assets/1744486/425543/f70af308-adb1-11e2-95f7-37323639314f.jpg)

**Comment by kjpou1** [comment] 2013-04-25 14:19
George

Thank you thank you thank you for your patience and your testing.

Any other problems let us know.

**Comment by kjpou1** [comment] 2013-04-25 14:19
Closing this one out

**Closed as completed by kjpou1** 2013-04-25 14:19 UTC

**Comment by imwower** [comment] 2013-04-25 14:38
iam just a beginner, and glad to help u~
